services:
  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
      - ./requirements.txt:/tmp/requirements.txt
    restart: always
    command:
      ["sh", "-c", "pip install --no-cache-dir -r /tmp/requirements.txt && start-notebook.sh"]

  qdrant:
    image: qdrant/qdrant:v1.12.4
    container_name: qdrant
    ports:
      - "6333:6333"
    environment:
      - QDRANT__SERVICE__LISTEN__HOST=0.0.0.0
      - QDRANT__SERVICE__LISTEN__PORT=6333
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: always

  postgres:
    image: postgres:12.22
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    restart: always

  langfuse:
    image: langfuse/langfuse:latest
    container_name: langfuse
    ports:
      - "3000:3000"
    environment:
      - LANGFUSE_HOST=${LANGFUSE_HOST}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - SALT=${SALT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - langfuse_storage:/data
    restart: always
    depends_on:
      - postgres

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODELS=${OLLAMA_MODELS}
    volumes:
      - ollama_storage:/data
    restart: always

volumes:
  qdrant_storage:
    driver: local

  langfuse_storage:
    driver: local

  postgres_storage:
    driver: local

  ollama_storage:
    driver: local

networks:
  llm-network:
    driver: bridge
