services:
  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGFUSE_HOST=${LANGFUSE_HOST}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
    volumes:
      - ./volumes/jupyter/notebooks:/home/jovyan/work
      - ./requirements.txt:/tmp/requirements.txt
    restart: always
    command:
      ["sh", "-c", "pip install --no-cache-dir -r /tmp/requirements.txt && start-notebook.sh"]
    networks:
      - llm-network

  postgres:
    image: postgres:12.22
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    restart: always
    networks:
      - llm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  langfuse:
    image: langfuse/langfuse:latest
    container_name: langfuse
    ports:
      - "3000:3000"
    environment:
      - LANGFUSE_HOST=${LANGFUSE_HOST}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${LANGFUSE_HOST}
      - SALT=${SALT}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    volumes:
      - langfuse_storage:/data
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - llm-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    volumes:
      - ./volumes/ollama:/mnt
      - ollama_storage:/root/.ollama
    restart: always
    networks:
      - llm-network

  qdrant:
    image: qdrant/qdrant:v1.12.4
    container_name: qdrant
    ports:
      - "6333:6333"
    environment:
      - QDRANT__SERVICE__LISTEN__HOST=0.0.0.0
      - QDRANT__SERVICE__LISTEN__PORT=6333
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: always
    networks:
      - llm-network

volumes:
  qdrant_storage:
    name: qdrant_storage
    driver: local
  langfuse_storage:
    name: langfuse_storage
    driver: local
  postgres_storage:
    name: postgres_storage
    driver: local
  ollama_storage:
    name: ollama_storage
    driver: local

networks:
  llm-network:
    driver: bridge
